-- AlterEnum
ALTER TYPE "AnalyticsEventType" ADD VALUE 'SEARCH_OPENED';
ALTER TYPE "AnalyticsEventType" ADD VALUE 'SEARCH_RESULT_CLICK';
ALTER TYPE "AnalyticsEventType" ADD VALUE 'CALENDAR_INTERACTION';
ALTER TYPE "AnalyticsEventType" ADD VALUE 'EXPLORE_INTERACTION';
