import { db } from "@/lib/db";
import type { Session } from "next-auth";
import type { ContentType, MediaType } from "@prisma/client";
import { requireAdmin, friendlyDbError } from "@/features/admin/service";
import { audit } from "@/lib/audit";

export interface AdminMediaListFilters {
  contentType?: ContentType;
  search?: string;
  page?: number;
}

const CONTENT_LABEL_QUERY: Record<ContentType, (ids: string[]) => Promise<{ id: string; name: string }[]>> = {
  FESTIVAL: (ids) => db.festival.findMany({ where: { id: { in: ids } }, select: { id: true, name: true } }),
  DESTINATION: (ids) => db.destination.findMany({ where: { id: { in: ids } }, select: { id: true, name: true } }),
  EXPERIENCE: (ids) => db.experience.findMany({ where: { id: { in: ids } }, select: { id: true, name: true } }),
  FOOD: (ids) => db.food.findMany({ where: { id: { in: ids } }, select: { id: true, name: true } }),
  EVENT: (ids) => db.event.findMany({ where: { id: { in: ids } }, select: { id: true, name: true } }),
};

/** Media has no name of its own — every list view needs its parent content's name, resolved the same batched-per-type way Media's own polymorphic reads always are (see src/lib/content/resolve.ts). */
export async function adminListMedia(session: Session | null, filters: AdminMediaListFilters = {}) {
  requireAdmin(session);
  const page = filters.page ?? 1;
  const pageSize = 40;
  const where = { contentType: filters.contentType };

  const [items, total] = await Promise.all([
    db.media.findMany({ where, orderBy: [{ contentType: "asc" }, { contentId: "asc" }, { order: "asc" }], skip: (page - 1) * pageSize, take: pageSize }),
    db.media.count({ where }),
  ]);

  const idsByType = new Map<ContentType, string[]>();
  for (const item of items) idsByType.set(item.contentType, [...(idsByType.get(item.contentType) ?? []), item.contentId]);
  const labelEntries = await Promise.all([...idsByType.entries()].map(async ([type, ids]) => [type, await CONTENT_LABEL_QUERY[type](ids)] as const));
  const labelByKey = new Map<string, string>();
  for (const [type, rows] of labelEntries) for (const row of rows) labelByKey.set(`${type}:${row.id}`, row.name);

  const withLabels = items
    .map((item) => ({ ...item, contentLabel: labelByKey.get(`${item.contentType}:${item.contentId}`) ?? null }))
    .filter((item) => !filters.search || item.contentLabel?.toLowerCase().includes(filters.search!.toLowerCase()));

  return { items: withLabels, total, page, pageSize };
}

export interface MediaWriteInput {
  url: string;
  altText?: string;
  type?: MediaType;
  order?: number;
  contentType: ContentType;
  contentId: string;
}

/**
 * URL-reference only — there is no working binary-upload path in this
 * environment (`src/lib/media/storage.ts`'s `getUploadUrl` deliberately
 * throws until real storage credentials are configured; see
 * docs/architecture.md). This mirrors exactly how seed data already
 * populates `Media.url` — a real CDN/URL string, just typed in rather than
 * generated by a signed upload.
 */
export async function adminCreateMedia(session: Session | null, input: MediaWriteInput) {
  requireAdmin(session);
  try {
    const media = await db.media.create({
      data: { url: input.url, altText: input.altText, type: input.type ?? "IMAGE", order: input.order ?? 0, contentType: input.contentType, contentId: input.contentId },
    });
    await audit.record({ adminId: session.user.id, action: "created", entityType: "MEDIA", entityId: media.id, metadata: { contentType: input.contentType, contentId: input.contentId } });
    return media;
  } catch (error) {
    throw friendlyDbError(error);
  }
}

export async function adminUpdateMedia(session: Session | null, id: string, input: { altText?: string; order?: number }) {
  requireAdmin(session);
  const media = await db.media.update({ where: { id }, data: { altText: input.altText, order: input.order } });
  await audit.record({ adminId: session.user.id, action: "updated", entityType: "MEDIA", entityId: media.id });
  return media;
}

export async function adminDeleteMedia(session: Session | null, id: string) {
  requireAdmin(session);
  await db.media.delete({ where: { id } });
  await audit.record({ adminId: session.user.id, action: "deleted", entityType: "MEDIA", entityId: id });
}
